# Generated by Django 4.0 on 2024-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('video_link', models.URLField(blank=True)),
                ('photos', models.ImageField(upload_to='recipe_photos/')),
                ('review_section', models.TextField(blank=True)),
            ],
        ),
    ]
