# Generated by Django 5.1.1 on 2024-09-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='review_section',
            new_name='category',
        ),
    ]
